name: Deploy to Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build and HTML Linter Check
        run: |
          echo "Running pre-deployment checks..."
          npm install -g htmlhint
          htmlhint "**/*.html"
          ls -la
          echo "Linting complete successfully."

      - name: Deploy to EC2 Staging Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/staging
            cd /home/ubuntu/staging
            git pull origin staging || git clone -b staging https://github.com/HassanMaskeen/cloud-pipeline-pro.git .
            echo "Staging deployment completed successfully at $(date)!"
